### ISSUE TITLE
@slidy/svelte - Components composition

### ISSUE THREAD

**Issue by Valexr** [Valexr/Slidy#43]

**Comment by EricRovell** [comment]
This issue is important because the breaking up the component into parts makes the code cleaner and gives the user more options for customization. Right now there are several subcomponents implemented:

- `<Arrow />` - previous / next slide management;
- `<Pagination />` - pagination-like responsive navigation;
- `<Image />` - useful `<img />` wrapper for some custom behaviour like styling broken images etc.

There might be more available components in the future for user needs, but these ones will be for internal use (still, will be available for import to pass them as slots with some custom behaviour).
