### ISSUE TITLE
Make it fast in first render

### ISSUE THREAD

**Issue by rcapdepaula** [Valexr/Slidy#72]
How can I make slidy load faster in the first render?

https://beach-real-estate.vercel.app/

my code:

https://svelte.dev/repl/e7c021f121cc4d39929501daf4085c6b?version=3.48.0

**Comment by Valexr** [comment]
1. Yours code in REPL is not complete (not working)
2. Slidy loaded very fast because very small script - I think it's `{#if browser}` SvelteKit directive or maybe slow response in fetch()
3. This requests is very slow - check network tab in devtools:
![Screenshot 2022-05-09 at 07 17 51](https://user-images.githubusercontent.com/5656366/167339873-4c8e2a36-721b-44a1-9a9c-93c1f4f3a942.jpg)
4. In version 3 Slidy is fully SSR compatible & not needed browser check, but svelte template not in release now. You can try [@slidy/core](https://github.com/Valexr/Slidy/tree/master/packages/core) to make yours custom template with it.
5. REPL [example](https://svelte.dev/repl/e7a3683b13b342dc8ecfc1d9b2b806f6)
6. SvelteKit static site with Slidy version 3 [example](https://slidy-www.surge.sh)

**Comment by rcapdepaula** [comment]
Thank you Alexander, the problem is in Firebase.
